# Generated by Django 4.0.2 on 2022-02-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('species', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('length', models.IntegerField()),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
